apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-estate-ingress
  namespace: dev-real-estate
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        -  # Add your host
      secretName: # Add your TLS secret name
  rules:
    - host: # Add your host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-estate-api-service
                port:
                  number: 8080
