apiVersion: v1
kind: Service
metadata:
  name: real-estate-api-service
  namespace: dev-real-estate
spec:
  type: NodePort
  selector:
    app: real-estate
  ports:
    - port: 8080
      targetPort: 8080
